image: node:12.0.0

stages:
  - build
  - deploy

install_dependencies:
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    - npm install

deploy_prod:
  stage: deploy
  environment:
    name: production
    url: $FIREBASE_URL
  only:
    - master
  cache:
    policy: pull
    paths:
      - node_modules/
  script:
    - npm run build-prod
    - npm run deploy